services:
    plex:
        container_name: plex
        image: plexinc/pms-docker:latest
        restart: unless-stopped
        environment:
            - TZ=Asia/Hong_Kong
        network_mode: host
        volumes:
            - ${HDD}/Media:/data
            - ${HDD}/applications/plex/config:/config
            - ${HDD}/applications/plex/transcode:/transcode

    homer:
        build:
            context: ./homer/
            dockerfile: ./Dockerfile
            #To build from source, comment previous line and uncomment below
            #build: .
        volumes:
            - /home/edward-server/home_server/homer/public/assets:/www/assets
        ports:
            - 8080:8080
        environment:
          - UID=1000
          - GID=1000
        restart: unless-stopped

    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${HDD}/applications/sonarr:/config
            - ${HDD}/Media/Shows:/tv
            - ${HDD}/Media/Anime:/anime
            - ${HDD}/downloads:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped

    radarr:
        container_name: radarr
        image: ghcr.io/linuxserver/radarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${HDD}/applications/radarr:/configs
            - ${HDD}/Media/Movies:/movies
            - ${HDD}/downloads:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
    
    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - AUTO_UPDATE=true
        volumes:
        - ${HDD}/applications/jackett:/config
        - ${HDD}/downloads/torrent-blackhole:/downloads
        ports:
        - 9117:9117
        restart: unless-stopped
    
    transmission:
        image: ghcr.io/linuxserver/transmission
        container_name: transmission
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - USER=${USERNAME}
        - PASS=${PASSWORD}
        volumes:
        - ${HDD}/applications/transmission:/config
        - ${HDD}/downloads:/downloads
        - ${HDD}/downloads/torrent-blackhole:/watch
        ports:
        - 9091:9091
        - 51413:51413
        - 51413:51413/udp
        restart: unless-stopped