services:
  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${USERNAME}
      - PASS=${PASSWORD}
    volumes:
      - ${HDD}/applications/transmission:/config
      - ${HDD}/downloads:/downloads
      - ${HDD}/downloads/torrent-blackhole:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NZBGET_USER=${USERNAME}
      - NZBGET_PASS=${PASSWORD}
    volumes:
      - ${HDD}/applications/nzbget:/config
      - ${HDD}/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  homer:
    build:
      context: ./homer/
      dockerfile: ./Dockerfile
      #To build from source, comment previous line and uncomment below
      #build: .
    volumes:
      - /home/edward/home_server/homer/public/assets:/www/assets
    ports:
      - 8080:8080
    environment:
      - UID=${PUID}
      - GID=${PGID}
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "8191:8191"
    restart: unless-stopped

  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HDD}/applications/home_assistant:/config
    ports:
      - 8123:8123
    depends_on:
      - zwave
    restart: unless-stopped

  zwave:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=${TZ}
    network_mode: host
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_30e5fe2d8d74ec11bdd8ab5019c2d21c-if00-port0:/dev/zwave"
    volumes:
      - ${HDD}/applications/zwave:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
      - "8092:8092" # port for Z-Wave JS websocket server

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: home-syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HDD}/applications/syncthing:/var/syncthing
    network_mode: host
    restart: unless-stopped
