services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    network_mode: host
    volumes:
      - ${HDD}/Media:/data
      - ${HDD}/applications/plex/config:/config
      - ${HDD}/applications/plex/transcode:/transcode
    devices:
      - /dev/dri:/dev/dri

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HDD}/applications/sonarr:/config
      - ${HDD}/Media/Shows:/tv
      - ${HDD}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  sonarr_anime:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr_anime
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HDD}/applications/sonarr_anime:/config
      - ${HDD}/Media/Anime:/tv
      - ${HDD}/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HDD}/applications/radarr:/config
      - ${HDD}/Media/Movies:/movies
      - ${HDD}/Media/Comedy_Specials:/comedy_specials
      - ${HDD}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HDD}/applications/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HDD}/applications/bazarr:/config
      - ${HDD}/Media/Movies:/movies #optional
      - ${HDD}/Media/Shows:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${HDD}/applications/overseerr:/app/config
    restart: unless-stopped
