services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment:
      # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 #
    restart: always
    ports:
      - "9925:3000" #
    volumes:
      - ${HDD}/applications/mealie:/app/data/ #
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - ${HDD}/applications/mealie:/app/data/
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://192.168.50.10:8080
    restart: always
