services:
  satisfactory:
    container_name: "satisfactory"
    hostname: "satisfactory"
    image: "wolveix/satisfactory-server:latest"
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
    volumes:
      - ${HDD}/applications/satisfactory:/config
    environment:
      - MAXPLAYERS=5
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ROOTLESS=false
      - STEAMBETA=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
